version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      
    - location: script/start_server.sh
      timeout: 300
      
  

