version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: script/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: script/start_server
      timeout: 300
      runas: ec2-user
  

