version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root
hooks:
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: root
    - location: script/start_server.sh
      timeout: 300
      runas: root
      
  

