version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      
    - location: start_server
      timeout: 300
      
  

